style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/mauna-cloud/starter-template
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - doc
        - refactor
        - deploy
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      doc: Documentation
      refactor: Refactors
      deploy: Changes to deploy
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
