title: "Example docs site"
description: A Jekyll theme for documentation
baseurl: "/module/<MODULE>" # the subpath of your site, e.g. /blog
url: "https://docs.mauna.ai"

theme: just-the-docs

permalink: pretty
exclude:
  [
    "node_modules/",
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "script/",
    "LICENSE.txt",
    "lib/",
    "bin/",
    "Rakefile",
  ]

color_scheme: nil # or "dark"

# Enable or disable the site search
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Docs home":
    - "/home"

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-2709176-10
