// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var WritableStream$MaunaReasonWebStreams = require("@mauna/reason-web-streams/src/WritableStream.bs.js");

function createWritable(func) {
  return WritableStream$MaunaReasonWebStreams.make({
              start: undefined,
              write: (function (chunk, param) {
                  return Promise.resolve(Curry._1(func, chunk));
                }),
              close: undefined,
              abort: undefined,
              type_: undefined
            }, undefined, undefined);
}

function useWritable(writable) {
  var writer = writable.getWriter();
  var close = function (param) {
    return writer.close();
  };
  var write = function (param) {
    return writer.write(param);
  };
  var releaseLock = function (param) {
    writer.releaseLock();
    
  };
  React.useEffect((function () {
          return releaseLock;
        }), ([]));
  return /* tuple */[
          write,
          close
        ];
}

exports.createWritable = createWritable;
exports.useWritable = useWritable;
/* react Not a pure module */
