// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./pipes/utils");
var $$TransformStream = require("@mauna/reason-web-streams/src/TransformStream.bs.js");
var Tee = require("./pipes/build/pipes/core/tee");
var Pipe = require("./pipes/build/pipes/core/pipe");
var Chain = require("./pipes/build/pipes/core/chain");
var Zip = require("./pipes/build/pipes/readable/zip");
var Sequence = require("./pipes/build/pipes/core/sequence");
var Merge = require("./pipes/build/pipes/readable/merge");

function make(prim) {
  return Pipe.default(prim);
}

function chain2(prim, prim$1) {
  return Chain.default(prim[1], prim$1[1]);
}

function chain3(prim, prim$1, prim$2) {
  return Chain.default(prim[1], prim$1[1], prim$2[1]);
}

function chain4(prim, prim$1, prim$2, prim$3) {
  return Chain.default(prim[1], prim$1[1], prim$2[1], prim$3[1]);
}

function chain5(prim, prim$1, prim$2, prim$3, prim$4) {
  return Chain.default(prim[1], prim$1[1], prim$2[1], prim$3[1], prim$4[1]);
}

function chain6(prim, prim$1, prim$2, prim$3, prim$4, prim$5) {
  return Chain.default(prim[1], prim$1[1], prim$2[1], prim$3[1], prim$4[1], prim$5[1]);
}

function sequence(prim) {
  return Sequence.default();
}

function tee(prim) {
  return Tee.default(prim);
}

function zip(prim) {
  return Zip.default(prim);
}

function merge(prim) {
  return Merge.merge(prim);
}

function makeReadable(prim) {
  return Utils.makeReadable(prim);
}

function consume(prim) {
  return Utils.consume(prim);
}

var t = $$TransformStream.make({
      start: undefined,
      transform: (function (x, controller) {
          controller.enqueue(x + 10 | 0);
          
        }),
      flush: undefined
    }, undefined, undefined, undefined);

var a = Pipe.default((function (x) {
        return x + 20 | 0;
      }));

var b = Pipe.default((function (x) {
        return x - 15 | 0;
      }));

var c = Pipe.default((function (x) {
        return x + 6 | 0;
      }));

var p = chain4(/* `TransformStream */[
      755930860,
      t
    ], /* `Pipe */[
      892411982,
      a
    ], /* `Pipe */[
      892411982,
      b
    ], /* `Pipe */[
      892411982,
      c
    ]);

var readable = Utils.makeReadable([
      2,
      3,
      4,
      5
    ]);

var transformed = readable.pipeThrough(p);

var reader = transformed.getReader();

Utils.consume(reader).then((function (res) {
        console.log(res);
        return Promise.resolve(undefined);
      }));

exports.make = make;
exports.chain2 = chain2;
exports.chain3 = chain3;
exports.chain4 = chain4;
exports.chain5 = chain5;
exports.chain6 = chain6;
exports.sequence = sequence;
exports.tee = tee;
exports.zip = zip;
exports.merge = merge;
exports.makeReadable = makeReadable;
exports.consume = consume;
exports.t = t;
exports.a = a;
exports.b = b;
exports.c = c;
exports.p = p;
exports.readable = readable;
exports.transformed = transformed;
exports.reader = reader;
/* t Not a pure module */
