// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pipe$MaunaReasonPipes = require("./Pipe.bs.js");
var TransformStream$MaunaReasonWebStreams = require("@mauna/reason-web-streams/src/TransformStream.bs.js");

var t = TransformStream$MaunaReasonWebStreams.make({
      start: undefined,
      transform: (function (x, controller) {
          controller.enqueue(x + 10 | 0);
          
        }),
      flush: undefined
    }, undefined, undefined, undefined);

var a = Pipe$MaunaReasonPipes.make(function (x) {
      return x + 20 | 0;
    });

var b = Pipe$MaunaReasonPipes.make(function (x) {
      return x - 15 | 0;
    });

var c = Pipe$MaunaReasonPipes.make(function (x) {
      return x + 6 | 0;
    });

exports.t = t;
exports.a = a;
exports.b = b;
exports.c = c;
/* t Not a pure module */
